# Generated by Django 5.2.7 on 2025-10-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JeuDeDonnees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre du jeu de données')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('source_catalogue', models.CharField(max_length=100, verbose_name='Catalogue source')),
                ('id_source', models.CharField(max_length=255, unique=True, verbose_name='ID sur la source')),
                ('url_source', models.URLField(max_length=500, verbose_name='URL sur la source')),
                ('organisation', models.CharField(blank=True, max_length=255, null=True, verbose_name='Organisation')),
                ('date_creation_source', models.DateTimeField(blank=True, null=True, verbose_name='Date de création (source)')),
                ('date_modification_source', models.DateTimeField(blank=True, null=True, verbose_name='Date de modification (source)')),
                ('date_ajout_plateforme', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout (plateforme)")),
                ('date_maj_plateforme', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour (plateforme)')),
            ],
            options={
                'verbose_name': 'Jeu de Données',
                'verbose_name_plural': 'Jeux de Données',
            },
        ),
    ]
